### ISSUE TITLE
Not OK boomer

### ISSUE THREAD

**Issue by Glutexo** [michalkasparek/Kiki#2]
Nejsem jsi úplně jistý, jestli se jedná o vhodné pojmenování modulu. Obsahuje upozornění např. na osoby s postižením či homosexuály, ale sám nese stereotypizující slovo „boomer“ v názvu. Ba bych se neštítil přímo toto slovo s vysvětlením naopak zařadit do slovníku.

**Comment by Glutexo** [comment]
@michalkasparek Co myslíš?

**Comment by michalkasparek** [comment]
Dobrá připomínka. Podstatný rozdíl vidím v tom, že nekorektní nebo stereotypizující fráze uvedené ve slovníku tohoto modulu jsou arogantní směrem dolů: k lidem, kteří to mají alespoň v nějakém ohledu těžší než většina. „OK boomer“ je v kontextu Česka roku 2022 téměř vždy arogantní směrem nahoru: schytávají ji prakticky výhradně vlivní, bohatí muži, kteří se přehlíživě vyjadřují k věcem mimo svoji životní zkušenost. Proto proti ní nic nemám.

**Comment by Glutexo** [comment]
Dobrá připomínka! Pořád mi nepřijde dobré, že je více v pořádku stereotypizovat někoho, kdo to má v životě lehké, než někoho, kdo štěstí tolik neměl. Postoj jsi mi ale vysvětlil pochopitelně. Děkuji! 👍🏻

**Comment by Glutexo** [comment]
A děkuji, žes mi sem nenapsal jen: „OK boomer.“ 😃

**Comment by michalkasparek** [comment]
Plot twist navíc je, že někteří boomeři to původně vůbec neměli lehké a svůj status si zaslouží… Ale tak nějak v té frázi pořád ještě nevidím takový mor jako v jiných. Díky za příležitost si to i pro sebe zverbalizovat.
